# This section is necessary for the way in which Blowfish
# uses il8n, probably.
languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
# true if right-to-left (RTL) language
rtl = false

# Some important defaults
title = "cdell.io"
# Removing the logo for now
# logo = "placeholder-logo.jpg"
description = "Christian Elliott's personal website"
copyright = "﫥 Christian Elliott 2022"

# This comes from https://gohugo.io/functions/format/#gos-layout-string
dateFormat = "2 January 2006"

[author]
  name = "Christian Elliott"
  # The image file must be in $PROJECT_ROOT/assets
  image = "img/author-placeholder.jpg"
  # headline = "an online brain dump"
  # headline = "my 🧠, your 👀" # Tbh this looks weird idk why
  headline = "my intrusive thoughts, your entertainment?"
  bio = "Thanks for reading. Christian Elliott - dreamer, engineer, watcher of RuneScape YT, caught in between gen-z and millennial {{< icon \"heart\" >}}"
  links = [
    { email = "mailto:cdelliott96@gmail.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/c-elliott96" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://www.linkedin.com/in/christian-elliott-b32921180/" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]
